name: Mypy Type Checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Installling Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          pip install mypy

      - name: Run mypy
        run: |
          mypy src/
